version: '3.8'
services:
  super-hero-front:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: super-hero-front
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src